### ISSUE TITLE
联合挖矿任务没有及时clean导致孤块率高的问题

### ISSUE THREAD

**Issue by onigirisan** [btccom/btcpool-ABANDONED#442]
现行的代码只在主链高度更新时才会下发 clean job，而联合挖矿高度更新是没有及时下发 clean job 导致联合挖矿孤块率高
isMergedMiningUpdate
https://github.com/btccom/btcpool/blob/32eef3db2d22113d37817c9e3a0b508c800cc8a5/src/bitcoin/JobMakerBitcoin.cc#L494-L502

createStratumJobEx
https://github.com/btccom/btcpool/blob/32eef3db2d22113d37817c9e3a0b508c800cc8a5/src/bitcoin/StratumServerBitcoin.cc#L251-L272

sendnotify
https://github.com/btccom/btcpool/blob/32eef3db2d22113d37817c9e3a0b508c800cc8a5/src/bitcoin/StratumServerBitcoin.cc#L136-L139

https://github.com/btccom/btcpool/blob/32eef3db2d22113d37817c9e3a0b508c800cc8a5/src/StratumServer.cc#L345-L356

sendnotify
https://github.com/btccom/btcpool/blob/32eef3db2d22113d37817c9e3a0b508c800cc8a5/src/bitcoin/StratumSessionBitcoin.cc#L133-L136

**Comment by rocqina** [comment]
这个无解吧，矿机只有接收到clean为true才会把之前的任务清掉。而联合挖矿出新块任务没理由让矿机清掉之前有效的主币任务，如果因为联合挖矿出新块而发送clean为true notify更新矿机的任务，会造成算力损失

**Comment by YihaoPeng** [comment]
如果收到clean字段为true的任务，矿机会立即放弃当前的提交，并且可能会立即放弃尚未完成的运算。如果联合挖矿经常clean，可能会对矿机算力造成可见的影响。
当然，我从来没有实际对比过。如果有人可以提供对比数据，我非常乐于接受。
